version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
  jobs:
    lint:
      executor: docker/machine
      steps:
        - checkout
        - docker:
            dockerfile: path/to/and/name/of/Dockerfile
            treat-warnings-as-errors: true
workflows:
  lint-dockerfile:
    jobs:
      - lint


# version: '2.1'
# orb:
  # jobs:
    # lintdockerfile:
      # docker: 
# 
      # steps:
        # - checkout
        # - dockler/dockerlint
        # - run:
            # dockerfile: ./Dockerfile
            # treat-warnings-as-errors: true

# workflows:
  # lint-dockerfile:
    # jobs:
      # - lintdockerfile
  # test-app:
    # - testapp
  # build-app-karsajobs:
    # - buildappkarsajobs