version: '2.1'
orb:
  jobs:
    lintdockerfile:
      docker: circleci/docker@2.2.0

      steps:
        - checkout
        - dockler/dockerlint:
            dockerfile: ./Dockerfile
            treat-warnings-as-errors: true

workflows:
  lint-dockerfile:
    jobs:
      - lintdockerfile
  # test-app:
    # - testapp
  # build-app-karsajobs:
    # - buildappkarsajobs