version: 2.1 #Version CircleCI
orbs: #orbs
  docker: circleci/docker@2.2.0 #Declare orbs docker dengan isi circleci/docker@2.2.0
jobs: #Setting jobs
  lint-dockerfile: #Setting Jobs lint-dockerfile
    executor: docker/machine #Mengunakan orbs docker dengan element machine
    steps: #Setting steps Jobs lint-dockerfile
      - checkout #Melakukan checkout script
      - docker/dockerlint: #Melakukan Menjalankan perintah dockerlint
          dockerfile: ./Dockerfile #Setting lokasi Dockerfile
          treat-warnings-as-errors: true #Setting bila ada warning akan dibilang sebagai error
  test-app: #Setting Jobs test-app
    docker: #Setting docker image yang digunakan di jobs test-app
      - image: cimg/go:1.18.1 #Mengunakan docker image go
    resource_class: large #Setting resource class
    steps: #Setting steps Jobs test-app
      - checkout #Melakukan checkout script
      - run: #Melakukan menjalan command
          command: go test -v -short --count=1 $(go list ./...) #Command perintah unit test
          name: run unit test #Command nama step
  build-app-karsajobs: #Setting build-app-karsajobs
    executor: docker/docker #Mengunakan orbs docker dengan element docker
    steps:
      - checkout #Melakukan checkout script
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t ghcr.io/$Username/karsajobs:latest .
      - deploy:
          name: Push image to github
          command: |
            echo $PASSWORD_GITHUB | docker login ghcr.io -u $Username --password-stdin
            docker push ghcr.io/$Username/karsajobs:latest

workflows:
  version: 2
  workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
