version: '2.1'
jobs:
  lintdockerfile:
    docker:
      - image: circleci/docker@2.2.0

    steps:
      - checkout
      - dockerlint:
          dockerfile: ./Dockerfile
          treat-warnings-as-errors: true

workflows:
  sample:
    lint-dockerfile:
      jobs:
        - lintdockerfile
    # test-app:
      # - testapp
    # build-app-karsajobs:
      # - buildappkarsajobs