version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  lint-dockerfile:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: ./Dockerfile
          treat-warnings-as-errors: true
  test-app:
    docker:
      - image: cimg/go:1.18.1
    resource_class: large
    steps:
      - checkout
      - run:
          command: go test -v -short --count=1 $(go list ./...)
          name: go test
  build-app-karsajobs:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Save Docker image layer cache
          command: |
            docker build -t ghcr.io/$Username/karsajobs:latest .
      - deploy:
          name: Push application Docker image
          command: |
            echo $PASSWORD_GITHUB | docker login ghcr.io -u $Username --password-stdin
            docker push ghcr.io/$Username/karsajobs:latest

workflows:
  version: 2
  workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
