version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  go: cimg/go:1.18.1
jobs:
  lint-dockerfile:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: ./Dockerfile
          treat-warnings-as-errors: true
  test-app:
    executor: go/default
    parallelism: 4
    resource_class: large
    working_directory: ./
    steps:
      - run:
          command: go test -v -short --count=1 $(go list ./...)
          name: go test
workflows:
  workflow:
    jobs:
      - lint-dockerfile
      - test-app
