version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.1
jobs:
  lint-dockerfile:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: ./Dockerfile
          treat-warnings-as-errors: true
  test-app:
    executor: 
      name: go/default
      tag: '1.16'
    steps:
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          command: go test -v -short --count=1 $(go list ./...)
          name: go test
workflows:
  lint-dockerfile:
    jobs:
      - lint-dockerfile
  test-app:
    jobs:
      - test-app
