apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
      - name: karsajobs
        image: "ghcr.io/jimmyready89/karsajobs:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: MONGO_HOST
            value: "mongodb"
          - name: APP_PORT
            value: "8080"
          - name: MONGO_USER
            value: "admin"
          - name: MONGO_PASS
            value: "supersecretpassword"